[email]
subject = "Late Midyear Update | Nathan Pham | Application ID: {{application_id}}"
body = """
Dear college admissions,

My name is Nathan Pham, and I attend Del Oro High School in Loomis, California. I am interested in attending {{university_name}} and wanted to update you on significant aspects of my application. I am now a confirmed National Merit Finalist and recipient of the Seal of Biliteracy for Spanish. Additionally, after completing a series of rigorous interviews, Replit (a collaborative browser based IDE) offered me a workspace engineering role. I have also changed my school schedule to better align with my long term career goals.

Thank you for considering my application. If you have any questions, please let me know.

Best,
Nathan Pham

[nathanpham.me](https://nathanpham.me)  
[github/nathan-pham](https://github.com/nathan-pham)
"""

[recipient]
universities = [
    { email = "admissions@mit.edu", application_id = "TEST", university_name = "MIT" },
    { email = "admission@brown.edu", application_id = "", university_name = "Brown University" },
    { email = "undergrad-admissions@duke.edu", application_id = "", university_name = "Duke University" },
    { email = "college@fas.harvard.edu", application_id = "", university_name = "Harvard University" },
    { email = "uaoffice@princeton.edu", application_id = "", university_name = "Princeton University" },
    { email = "sarahyoon@princeton.edu", application_id = "", university_name = "Princeton University" },
    { email = "karen.ransom@stanford.edu", application_id = "", university_name = "Stanford University" },
    { email = "reply@dartmouth.edu", application_id = "", university_name = "Dartmouth" },
    { email = "info@admissions.upenn.edu", application_id = "", university_name = "University of Pennsylvania" },
    { email = "student.questions@yale.edu", application_id = "", university_name = "Yale University" },
    { email = "admission@rice.edu", application_id = "", university_name = "Rice University" },
    { email = "emejia17@usc.edu", application_id = "", university_name = "University of Southern California" },
    { email = "ugadm@saonet.ucla.edu", application_id = "", university_name = "UCLA" },
    { email = "readmission@berkeley.edu", application_id = "", university_name = "UC Berkeley" },
    { email = "ugadmissions@caltech.edu", application_id = "", university_name = "Caltech" },
    { email = "admission@andrew.cmu.edu", application_id = "", university_name = "Carnegie Mellon University" },
    { email = "admissions@nyu.edu", application_id = "", university_name = "NYU" },
]
